## PRDA – 04 Job Market Analysis

In [1]:
# Import required libraries
import pandas as pd
import numpy as np

In [3]:
# Load dataset
df = pd.read_csv(r'C:\Users\puspa\OneDrive\Desktop\Job_Market_ Analysis\Job_Market_Analysis.csv')

In [4]:
# Display all columns and rows in the DataFrame
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [5]:
# display rows to understand data
df.head(101)

,Job_Title,Salary_Estimate,Company_Name,Location,Headquarters,Industry,Sector,Revenue,Competitors,Hourly,Employer_provided,Min_Salary,Max_Salary,Avg_Salary,company_txt,Job_Location,Python,Spark,AWS,Excel,SQL,SAS,Keras,PyTorch,Scikit_Learn,TensorFlow,Hadoop,Tableau,Power_BI,Flink,MongoDB,Google_Analytics,Job_Category,Seniority_Title,Degree_Required,Company_Rating,State_Wise,Company_Man_Power,Company_Man_Power_Category,Founded_Year,Company_Age,Ownership_Type
0,data scientist,$53K-$91K (Glassdoor est.),Tecolote Research,"Albuquerque, NM","Goleta, CA",Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0,Tecolote Research,NM,1,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,Data Scientist,Not Specified,Masters,3.8,NM,501 - 1000,Medium,1973.0,53.0,Private
1,healthcare data scientist,$63K-$112K (Glassdoor est.),University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5,University of Maryland Medical System,MD,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.4,MD,10000+,Very Large,1984.0,42.0,Other
2,data scientist,$80K-$90K (Glassdoor est.),KnowBe4,"Clearwater, FL","Clearwater, FL",Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4,FL,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.8,FL,501 - 1000,Medium,2010.0,16.0,Private
3,data scientist,$56K-$97K (Glassdoor est.),PNNL,"Richland, WA","Richland, WA",Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL,WA,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.8,WA,1001 - 5000,Large,1965.0,61.0,Government
4,data scientist,$86K-$143K (Glassdoor est.),Affinity Solutions,"New York, NY","New York, NY",Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions,NY,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,2.9,NY,51 - 200,Small,1998.0,28.0,Private
5,data scientist,$71K-$119K (Glassdoor est.),CyrusOne,"Dallas, TX","Dallas, TX",Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71,119,95.0,CyrusOne,TX,1,0,1,1,1,0,0,0,0,0,0,0,1,0,1,0,Data Scientist,Not Specified,Not_Specified,3.4,TX,201 - 500,Medium,2000.0,26.0,Public
6,data scientist,$54K-$93K (Glassdoor est.),ClearOne Advantage,"Baltimore, MD","Baltimore, MD",Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54,93,73.5,ClearOne Advantage,MD,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.1,MD,501 - 1000,Medium,2008.0,18.0,Private
7,data scientist,$86K-$142K (Glassdoor est.),Logic20/20,"San Jose, CA","Seattle, WA",Consulting,Business Services,$25 to $50 million (USD),-1,0,0,86,142,114.0,Logic20/20,CA,1,1,1,1,1,0,0,1,0,1,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.8,CA,201 - 500,Medium,2005.0,21.0,Private
8,research scientist,$38K-$84K (Glassdoor est.),Rochester Regional Health,"Rochester, NY","Rochester, NY",Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0,38,84,61.0,Rochester Regional Health,NY,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Other Scientist,Not Specified,PhD,3.3,NY,10000+,Very Large,2014.0,12.0,Healthcare
9,data scientist,$120K-$160K (Glassdoor est.),<intent>,"New York, NY","New York, NY",Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120,160,140.0,<intent>,NY,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.6,NY,51 - 200,Small,2009.0,17.0,Private
10,data scientist,$126K-$201K (Glassdoor est.),Wish,"San Jose, CA","San Francisco, CA",Other Retail Stores,Retail,$1 to $2 billion (USD),-1,0,0,126,201,163.5,Wish,CA,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.5,CA,501 - 1000,Medium,2011.0,15.0,Private
11,data scientist,$64K-$106K (Glassdoor est.),ManTech,"Chantilly, VA","Herndon, VA",Research & Development,Business Services,$1 to $2 billion (USD),-1,0,0,64,106,85.0,ManTech,VA,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.1,VA,5001 - 10000,Large,1968.0,58.0,Public
12,staff data scientist technology,$106K-$172K (Glassdoor est.),Walmart,"Plano, TX","Bentonville, AR","Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon",0,0,106,172,139.0,Walmart,TX,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.2,TX,10000+,Very Large,1962.0,64.0,Public
13,data analyst,$46K-$85K (Glassdoor est.),Yesler,"Seattle, WA","Seattle, WA",Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,46,85,65.5,Yesler,WA,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,0,Data Analyst,Not Specified,Not_Specified,4.1,WA,201 - 500,Medium,2012.0,14.0,Private
14,data scientist,$83K-$144K (Glassdoor est.),Takeda Pharmaceuticals,"Cambridge, MA","OSAKA, Japan",Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer",0,0,83,144,113.5,Takeda Pharmaceuticals,MA,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.7,MA,10000+,Very Large,1781.0,245.0,Public
15,data engineer i,$102K-$190K (Glassdoor est.),Audible,"Newark, NJ","Newark, NJ",Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1,0,0,102,190,146.0,Audible,NJ,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Engineer,Not Specified,Not_Specified,3.6,NJ,1001 - 5000,Large,1995.0,31.0,Subsidiary
16,scientist i ii biology,$67K-$137K (Glassdoor est.),Blueprint Medicines,"Cambridge, MA","Cambridge, MA",Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene",0,0,67,137,102.0,Blueprint Medicines,MA,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Other Scientist,Not Specified,PhD,3.9,MA,51 - 200,Small,2011.0,15.0,Public
17,customer data scientist,$118K-$189K (Glassdoor est.),h2o.ai,"Mountain View, CA","Mountain View, CA",Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,118,189,153.5,h2o.ai,CA,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.3,CA,201 - 500,Medium,2011.0,15.0,Private
18,data scientist health data analytics,$110K-$175K (Glassdoor est.),Nuna,"San Francisco, CA","San Francisco, CA",Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5,Nuna,CA,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.2,CA,51 - 200,Small,2010.0,16.0,Private
19,data scientist,$64K-$111K (Glassdoor est.),Pinnacol Assurance,"Denver, CO","Denver, CO",Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,64,111,87.5,Pinnacol Assurance,CO,1,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.0,CO,501 - 1000,Medium,1915.0,111.0,Nonprofit
20,data scientist,$81K-$130K (Glassdoor est.),Porch,"Seattle, WA","Seattle, WA",Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack",0,0,81,130,105.5,Porch,WA,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.2,WA,201 - 500,Medium,2012.0,14.0,Private
21,senior data scientist machine learning,$73K-$119K (Glassdoor est.),Health IQ,"Dallas, TX","Mountain View, CA",Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1,0,0,73,119,96.0,Health IQ,TX,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Senior,PhD,3.9,TX,201 - 500,Medium,2013.0,13.0,Private
22,data scientist quantitative,$86K-$139K (Glassdoor est.),Truckstop.com,"Chicago, IL","New Plymouth, ID",Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1,0,0,86,139,112.5,Truckstop.com,IL,1,0,1,1,1,0,0,0,0,0,0,0,0,0,1,0,Data Scientist,Not Specified,Masters,3.8,IL,501 - 1000,Medium,1995.0,31.0,Private
23,data scientist,$63K-$105K (Glassdoor est.),SMC 3,"Louisville, KY","Peachtree City, GA",Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1,0,0,63,105,84.0,SMC 3,KY,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,Data Scientist,Not Specified,Masters,4.3,KY,51 - 200,Small,1935.0,91.0,Nonprofit
24,data scientist,$109K-$177K (Glassdoor est.),Novetta,"Herndon, VA","Mc Lean, VA",Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton",0,0,109,177,143.0,Novetta,VA,1,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.0,VA,501 - 1000,Medium,2012.0,14.0,Private
25,digital health data scientist,$63K-$110K (Glassdoor est.),Pfizer,"Cambridge, MA","New York, NY",Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63,110,86.5,Pfizer,MA,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.0,MA,10000+,Very Large,1849.0,177.0,Public
26,data scientist,$75K-$124K (Glassdoor est.),First Tech Federal Credit Union,"Hillsboro, OR","San Jose, CA",Banks & Credit Unions,Finance,$100 to $500 million (USD),-1,0,0,75,124,99.5,First Tech Federal Credit Union,OR,1,1,1,1,1,0,1,0,1,1,0,1,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.5,OR,1001 - 5000,Large,1952.0,74.0,Private
27,associate data analyst,$34K-$61K (Glassdoor est.),The Hanover Insurance Group,"Worcester, MA","Worcester, MA",Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0,0,34,61,47.5,The Hanover Insurance Group,MA,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Analyst,Not Specified,Not_Specified,3.7,MA,5001 - 10000,Large,1852.0,174.0,Public
28,clinical data scientist,$63K-$105K (Glassdoor est.),Pfizer,"Groton, CT","New York, NY",Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63,105,84.0,Pfizer,CT,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.0,CT,10000+,Very Large,1849.0,177.0,Public
29,data scientist,$80K-$90K (Glassdoor est.),KnowBe4,"Clearwater, FL","Clearwater, FL",Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4,FL,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.8,FL,501 - 1000,Medium,2010.0,16.0,Private
30,data scientist,$56K-$97K (Glassdoor est.),PNNL,"Richland, WA","Richland, WA",Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL,WA,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.8,WA,1001 - 5000,Large,1965.0,61.0,Government
31,data scientist,$72K-$120K (Glassdoor est.),Amrock,"Detroit, MI","Detroit, MI",Real Estate,Real Estate,$500 million to $1 billion (USD),-1,0,0,72,120,96.0,Amrock,MI,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.6,MI,1001 - 5000,Large,1997.0,29.0,Private
32,data scientist machine learning expert,$86K-$143K (Glassdoor est.),Novartis,"Cambridge, MA","Basel, Switzerland",Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,86,143,114.5,Novartis,MA,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.8,MA,10000+,Very Large,1996.0,30.0,Public
33,data scientist,$93K-$149K (Glassdoor est.),Juniper Networks,"Sunnyvale, CA","Sunnyvale, CA",Telecommunications Services,Telecommunications,$2 to $5 billion (USD),-1,0,0,93,149,121.0,Juniper Networks,CA,1,1,0,1,1,0,1,0,1,1,0,0,0,0,1,0,Data Scientist,Not Specified,Masters,3.8,CA,5001 - 10000,Large,1996.0,30.0,Public
34,data scientist,$85K-$140K (Glassdoor est.),New England Biolabs,"Ipswich, MA","Ipswich, MA",Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Thermo Fisher Scientific, Enzymatics, Illumina",0,0,85,140,112.5,New England Biolabs,MA,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.7,MA,201 - 500,Medium,1974.0,52.0,Private
35,web data analyst,$77K-$135K (Glassdoor est.),Clarity Insights,"San Jose, CA","Chicago, IL",IT Services,Information Technology,Unknown / Non-Applicable,-1,0,0,77,135,106.0,Clarity Insights,CA,1,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,Data Analyst,Not Specified,Not_Specified,4.2,CA,201 - 500,Medium,2008.0,18.0,Private
36,data scientist,$82K-$132K (Glassdoor est.),Esri,"Redlands, CA","Redlands, CA",Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),Pitney Bowes,0,0,82,132,107.0,Esri,CA,1,1,1,0,0,0,0,0,0,0,1,1,0,0,1,0,Data Scientist,Not Specified,Masters,3.5,CA,1001 - 5000,Large,1969.0,57.0,Private
37,data scientist,$83K-$137K (Glassdoor est.),Systems & Technology Research,"Woburn, MA","Woburn, MA",Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1,0,0,83,137,110.0,Systems & Technology Research,MA,1,1,0,1,1,0,0,1,1,1,1,0,0,0,0,0,Data Scientist,Not Specified,PhD,4.7,MA,201 - 500,Medium,2010.0,16.0,Private
38,senior data scientist,$115K-$180K (Glassdoor est.),Sartorius,"Fremont, CA","Gottingen, Germany",Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1,0,0,115,180,147.5,Sartorius,CA,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Senior,Masters,3.5,CA,5001 - 10000,Large,1870.0,156.0,Public
39,data engineer,$74K-$138K (Glassdoor est.),Lancer Insurance,"Long Beach, NY","Long Beach, NY",Insurance Carriers,Insurance,$100 to $500 million (USD),-1,0,0,74,138,106.0,Lancer Insurance,NY,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,Data Engineer,Not Specified,Masters,3.5,NY,201 - 500,Medium,1985.0,41.0,Private
40,data analyst,$64K-$112K (Glassdoor est.),Sauce Labs,"San Francisco, CA","San Francisco, CA",IT Services,Information Technology,$50 to $100 million (USD),"BrowserStack, Selenium Master, Perfecto Mobile",0,0,64,112,88.0,Sauce Labs,CA,1,0,1,1,1,0,0,0,0,0,0,1,0,0,1,0,Data Analyst,Not Specified,Not_Specified,4.2,CA,201 - 500,Medium,2008.0,18.0,Private
41,data engineer,$68K-$129K (Glassdoor est.),Persivia,"Marlborough, MA","Lowell, MA",Unknown,Unknown,Less than $1 million (USD),-1,0,0,68,129,98.5,Persivia,MA,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,Data Engineer,Not Specified,Not_Specified,3.6,MA,Unknown,Unknown,NaN,NaN,Private
42,data scientist algorithms inference,$110K-$175K (Glassdoor est.),Nuna,"San Francisco, CA","San Francisco, CA",Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5,Nuna,CA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,4.2,CA,51 - 200,Small,2010.0,16.0,Private
43,scientist,$52K-$113K (Glassdoor est.),Edgewell Personal Care,"Allendale, NJ","Shelton, CT",Consumer Products Manufacturing,Manufacturing,$2 to $5 billion (USD),"Unilever, Procter & Gamble, Henkel",0,0,52,113,82.5,Edgewell Personal Care,NJ,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,Other Scientist,Not Specified,Masters,3.4,NJ,5001 - 10000,Large,2015.0,11.0,Public
44,senior data scientist,$110K-$150K(Employer est.),Equity Residential,"Chicago, IL","Chicago, IL",Real Estate,Real Estate,$2 to $5 billion (USD),"UDR, AvalonBay Communities, Essex Property Trust",0,0,110,150,130.0,Equity Residential,IL,1,1,0,1,1,0,0,0,1,0,1,1,1,0,0,0,Data Scientist,Senior,Masters,4.3,IL,1001 - 5000,Large,1993.0,33.0,Public
45,data scientist,Employer Provided Salary:$150K-$160K,BPA Services,"Washington, DC","Alexandria, VA",Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,1,150,160,155.0,BPA Services,DC,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,5.0,DC,Unknown,Unknown,NaN,NaN,Private
46,lead data scientist,$158K-$211K (Glassdoor est.),Visa Inc.,"Bellevue, WA","Foster City, CA",IT Services,Information Technology,$10+ billion (USD),"American Express, Mastercard, Discover",0,0,158,211,184.5,Visa Inc.,WA,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,Data Scientist,Senior,Not_Specified,3.7,WA,10000+,Very Large,1958.0,68.0,Public
47,associate data analyst,$20K-$39K (Glassdoor est.),Intrado,"Longmont, CO","Omaha, NE",Enterprise Software & Network Solutions,Information Technology,$2 to $5 billion (USD),-1,0,0,20,39,29.5,Intrado,CO,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Analyst,Not Specified,Masters,3.1,CO,5001 - 10000,Large,1986.0,40.0,Private
48,spectral scientist engineer,$56K-$117K (Glassdoor est.),Centauri,"Beavercreek, OH","Chantilly, VA",Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),"TASC, Vencore, Booz Allen Hamilton",0,0,56,117,86.5,Centauri,OH,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Other Scientist,Not Specified,Masters,4.7,OH,501 - 1000,Medium,1999.0,27.0,Private
49,college hire data scientist open to decemb...,$63K-$99K (Glassdoor est.),Caterpillar,"Peoria, IL","Deerfield, IL",Industrial Manufacturing,Manufacturing,$10+ billion (USD),"John Deere, Komatsu, CNH Industrial",0,0,63,99,81.0,Caterpillar,IL,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.7,IL,10000+,Very Large,1925.0,101.0,Public
50,data scientist,$68K-$114K (Glassdoor est.),Zimmerman Advertising,"Fort Lauderdale, FL","Fort Lauderdale, FL",Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,68,114,91.0,Zimmerman Advertising,FL,1,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.8,FL,501 - 1000,Medium,1984.0,42.0,Subsidiary
51,data scientist office of data science,$86K-$143K (Glassdoor est.),Liberty Mutual Insurance,"Boston, MA","Boston, MA",Insurance Carriers,Insurance,$10+ billion (USD),"Travelers, Allstate, State Farm",0,0,86,143,114.5,Liberty Mutual Insurance,MA,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.3,MA,10000+,Very Large,1912.0,114.0,Private
52,data science analyst,$41K-$95K (Glassdoor est.),"Torch Technologies, Inc.","Huntsville, AL","Huntsville, AL",Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1,0,0,41,95,68.0,"Torch Technologies, Inc.",AL,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.6,AL,1001 - 5000,Large,2002.0,24.0,Private
53,data scientist,$86K-$144K (Glassdoor est.),Swiss Re,"Armonk, NY","Zurich, Switzerland",Insurance Agencies & Brokerages,Insurance,$10+ billion (USD),"Munich Re, Hannover RE, SCOR",0,0,86,144,115.0,Swiss Re,NY,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.7,NY,10000+,Very Large,1863.0,163.0,Public
54,data scientist,$80K-$139K (Glassdoor est.),Northrop Grumman,"San Diego, CA","Falls Church, VA",Aerospace & Defense,Aerospace & Defense,$10+ billion (USD),-1,0,0,80,139,109.5,Northrop Grumman,CA,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,Data Scientist,Not Specified,Not_Specified,3.7,CA,10000+,Very Large,1939.0,87.0,Public
55,data scientist,$56K-$95K (Glassdoor est.),Sartorius,"Albuquerque, NM","Gottingen, Germany",Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1,0,0,56,95,75.5,Sartorius,NM,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Masters,3.5,NM,5001 - 10000,Large,1870.0,156.0,Public
56,data scientist,$120K-$189K (Glassdoor est.),Netskope,"San Francisco, CA","Santa Clara, CA",Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,"Skyhigh Networks, Zscaler, NortonLifeLock",0,0,120,189,154.5,Netskope,CA,1,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,Data Scientist,Not Specified,PhD,4.1,CA,501 - 1000,Medium,2012.0,14.0,Private
57,data scientist,$111K-$176K (Glassdoor est.),1904labs,"Saint Louis, MO","Saint Louis, MO",IT Services,Information Technology,Unknown / Non-Applicable,"Slalom, Daugherty Business Solutions",0,0,111,176,143.5,1904labs,MO,1,1,0,0,1,0,1,0,1,1,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.7,MO,51 - 200,Small,2016.0,10.0,Private
58,data scientist,$54K-$93K (Glassdoor est.),ClearOne Advantage,"Baltimore, MD","Baltimore, MD",Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54,93,73.5,ClearOne Advantage,MD,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Data Scientist,Not Specified,Not_Specified,4.1,MD,501 - 1000,Medium,2008.0,18.0,Private

In [6]:
# check datatype, null values, column info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 742 entries, 0 to 741
Data columns (total 42 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Job_Title                   742 non-null    object
 1   Salary_Estimate             742 non-null    object
 2   Company_Name                742 non-null    object
 3   Location                    742 non-null    object
 4   Headquarters                742 non-null    object
 5   Industry                    742 non-null    object
 6   Sector                      742 non-null    object
 7   Revenue                     742 non-null    object
 8   Competitors                 742 non-null    object
 9   Hourly                      742 non-null    int64
 10  Employer_provided           742 non-null    int64
 11  Min_Salary                  742 non-null    int64
 12  Max_Salary                  742 non-null    int64
 13  Avg_Salary                  742 non-null    float64
 14  company_txt                 742 non-null    object
 15  Job_Location                742 non-null    object
 16  Python                      742 non-null    int64
 17  Spark                       742 non-null    int64
 18  AWS                         742 non-null    int64
 19  Excel                       742 non-null    int64
 20  SQL                         742 non-null    int64
 21  SAS                         742 non-null    int64
 22  Keras                       742 non-null    int64
 23  PyTorch                     742 non-null    int64
 24  Scikit_Learn                742 non-null    int64
 25  TensorFlow                  742 non-null    int64
 26  Hadoop                      742 non-null    int64
 27  Tableau                     742 non-null    int64
 28  Power_BI                    742 non-null    int64
 29  Flink                       742 non-null    int64
 30  MongoDB                     742 non-null    int64
 31  Google_Analytics            742 non-null    int64
 32  Job_Category                742 non-null    object
 33  Seniority_Title             742 non-null    object
 34  Degree_Required             742 non-null    object
 35  Company_Rating              742 non-null    float64
 36  State_Wise                  742 non-null    object
 37  Company_Man_Power           742 non-null    object
 38  Company_Man_Power_Category  742 non-null    object
 39  Founded_Year                692 non-null    float64
 40  Company_Age                 692 non-null    float64
 41  Ownership_Type              742 non-null    object
dtypes: float64(4), int64(20), object(18)
memory usage: 243.6+ KB

## 1. States with Most Number of Jobs

In [7]:
state_jobs = df['State_Wise'].value_counts()

In [8]:
state_jobs.head(10)

State_Wise
CA    152
MA    103
NY     72
VA     41
IL     40
MD     35
PA     33
TX     28
NC     21
WA     21
Name: count, dtype: int64

## 2. Average Minimal and Maximal Salaries in Different States

In [10]:
state_salary = df.groupby('State_Wise')[['Min_Salary','Max_Salary']].mean().round(2)
state_salary.sort_values(by='Max_Salary', ascending=False).head(10)

            Min_Salary  Max_Salary
State_Wise
CA               92.43      154.60
IL               88.35      144.98
MA               78.69      136.30
NJ               76.82      132.29
DC               88.64      131.73
NC               69.05      127.86
KY               66.33      127.67
MD               68.31      126.40
RI               74.00      126.00
NY               72.12      125.18

## 3. Average Salary in Different States

In [13]:
Avg_Salary_State = df.groupby('State_Wise')['Avg_Salary'].mean().round(2)
Avg_Salary_State.sort_values(ascending=False).head(15)

State_Wise
CA    123.51
IL    116.66
DC    110.18
MA    107.50
NJ    104.56
MI    100.25
RI    100.00
NY     98.65
NC     98.45
MD     97.36
KY     97.00
VA     95.62
UT     94.15
PA     93.86
WA     93.19
Name: Avg_Salary, dtype: float64

## 4. Top 5 Industries with Maximum Job Postings

In [14]:
Top_Industries = df['Industry'].value_counts().head(5)
Top_Industries

Industry
Biotech & Pharmaceuticals           112
Insurance Carriers                   63
Computer Hardware & Software         59
IT Services                          50
Health Care Services & Hospitals     49
Name: count, dtype: int64

## 5. Companies with Maximum Job Openings

In [15]:
Top_Companies = df['Company_Name'].value_counts().head(15)
Top_Companies

Company_Name
MassMutual                          14
Reynolds American                   14
Takeda Pharmaceuticals              14
Software Engineering Institute      11
PNNL                                10
Liberty Mutual Insurance            10
AstraZeneca                          9
MITRE                                8
Numeric, LLC                         7
Advanced BioScience Laboratories     7
Fareportal                           7
Pfizer                               7
Novartis                             7
Rochester Regional Health            7
Novetta                              6
Name: count, dtype: int64

## 6. Job Titles with Most Number of Jobs

In [16]:
Top_Jobs = df['Job_Category'].value_counts()
Top_Jobs

Job_Category
Data Scientist     313
Other Scientist    143
Data Engineer      124
Data Analyst       109
ML Engineer         22
Manager             16
Other               10
Director             5
Name: count, dtype: int64

## 7. Salary of Job Titles with Most Number of Jobs

In [17]:
Job_Salary = df.groupby('Job_Category')['Avg_Salary'].mean().round(2)
Job_Salary.sort_values(ascending=False)

Job_Category
Director           130.80
ML Engineer        126.43
Data Scientist     118.29
Data Engineer      104.28
Other               91.45
Other Scientist     88.06
Manager             73.22
Data Analyst        66.34
Name: Avg_Salary, dtype: float64

## 8. Skills Required by Companies for Each Job Title

In [21]:
skill_cols = ['Python','Spark','AWS','Excel','SQL','SAS','Keras','PyTorch',
              'Scikit_Learn','TensorFlow','Hadoop','Tableau','Power_BI',
              'Flink','MongoDB','Google_Analytics']

In [22]:
skills_percent = df.groupby('Job_Category')[skill_cols].mean() * 100
skills_percent

,Python,Spark,AWS,Excel,SQL,SAS,Keras,PyTorch,Scikit_Learn,TensorFlow,Hadoop,Tableau,Power_BI,Flink,MongoDB,Google_Analytics
Job_Category,,,,,,,,,,,,,,,,
Data Analyst,33.027523,5.504587,9.174312,74.311927,72.477064,11.926606,0.000000,0.000000,0.000000,0.000000,2.752294,40.366972,17.431193,0.000000,2.752294,10.091743
Data Engineer,63.709677,54.838710,49.193548,46.774194,73.387097,0.806452,0.000000,0.000000,0.000000,1.612903,41.129032,8.870968,4.032258,4.838710,10.483871,0.000000
Data Scientist,76.677316,26.837061,25.239617,49.520767,56.230032,15.974441,9.265176,10.543131,15.015974,19.169329,19.169329,24.281150,8.945687,1.277955,6.070288,0.958466
Director,0.000000,0.000000,20.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ML Engineer,81.818182,18.181818,27.272727,31.818182,59.090909,0.000000,0.000000,22.727273,31.818182,40.909091,18.181818,0.000000,0.000000,0.000000,0.000000,0.000000
Manager,25.000000,0.000000,12.500000,68.750000,68.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,75.000000,12.500000,0.000000,0.000000,0.000000
Other,40.000000,50.000000,30.000000,90.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,60.000000,50.000000,20.000000,0.000000,20.000000,0.000000
Other Scientist,7.692308,0.000000,9.790210,45.454545,2.097902,1.398601,0.000000,0.699301,0.000000,0.699301,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

## 9. Relation between Average Salary and Education

In [23]:
Degree_Salary = df.groupby('Degree_Required')['Avg_Salary'].mean().round(2)
Degree_Salary.sort_values(ascending=False)

Degree_Required
PhD              115.98
Masters          105.63
Not_Specified     94.70
Name: Avg_Salary, dtype: float64

## 10. Important insights

1. Python,Excel,SQL are most in-demand skills.
2. CA State and MA State have highest job opportunities.
3. Data Scientist roles offer highest average salary.
4. Larger companies offer higher salaries.
5. Higher education (PhD) correlates with higher salary.